### ISSUE TITLE
Issue with looping workflow and undefined execution order

### ISSUE THREAD

**Issue by Dobidop** [palant/integrated-nodes-comfyui#2]
Most likely not an issue with the integrated nodes, but connecting integrated nodes like this will give ComfyUI some (understandable) issues when determining what order to execute the nodes. Not sure if this could be addressed inside the integrated-nodes custom node.
![issue](https://github.com/palant/integrated-nodes-comfyui/assets/67412288/fc1b70e8-7cda-4149-bd10-845aa8c4d624)

This is based on the default workflow where everything but the text prompt is included in the main integrated node.

Not sure if this is would be included in what you address the section "Using custom nodes in integrated nodes" in the readme.

**Comment by palant** [comment]
Yes, I’ve had this issue as well. There isn’t anything I can do about that. As far as ComfyUI is concerned, an integrated node is just a single node. So it cannot get data from a node that it feeds data into.

In this particular case you probably need to put the checkpoint loader outside the integrated node, that’s what I do. Means quite a few additional connections of course, but that’s what I have [AutoConnect](https://github.com/palant/autoconnect-comfyui/) for. An alternative would be loading CLIP separately, maybe integrated into the double prompt.

I do not really see how this issue can be described in the README in a meaningful way.
