### ISSUE TITLE
Fix for untyped hidden inputs

### ISSUE THREAD

**Issue by OverkillAnalytics** [palant/integrated-nodes-comfyui#4]
Love this repo!

Quick note - I had an issue with untyped hidden nodes raising an error (i.e., another custom node maker failed to type their hidden input).  I changed this line:

https://github.com/palant/integrated-nodes-comfyui/blob/da2d7b49d8111685e53fa942a9e58e3d95017fb1/integrated_nodes.py#L58C1-L58C53

to:

 `           elif hasattr(exported_inputs[name], "type") and exported_inputs[name].type != type:
`

and it fixed my issue. Assume it's OK to allow the node if the hidden input is untyped rather than a conflicting type. Thanks!

**Comment by palant** [comment]
That’s not an issue with that custom node, it’s a bug in my code. `HiddenInput` has no `type` attribute, it’s called `descriptor`. I guess I’ve never had an integrated node where some hidden input was being used twice. This code should actually be:

```python
            elif exported_inputs[name].descriptor != type:
```

I’ll need to test this change when I have a bit of time.

**Comment by palant** [comment]
I’ve turned this error into a warning: in my tests, ComfyUI will happily accept type mismatches when it comes to hidden inputs. Types are only validated for visible inputs, when these are connected. So it makes no sense for me to enforce correct types here.
