### ISSUE TITLE
This is cool, it's basically giving you the ability to create functions! 

### ISSUE THREAD

**Issue by ghostsquad** [palant/integrated-nodes-comfyui#6]
It might be worth mentioning in the readme or even renaming the repo, this basically gives you the ability to create "functions" (for those of us with a software development background).

This is a really powerful concept!

**Comment by palant** [comment]
It’s rather a grouping approach. In fact, I see that https://github.com/comfyanonymous/ComfyUI/pull/1776 landed in ComfyUI – it does pretty much the same thing on the client side. So I’m definitely not adding programming terminology into the mix, it will confuse even the people who understand it.
